services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testU
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local_network

  app:
    build: ./backend
    container_name: spring-app
    depends_on:
      - db
      - authentication
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: testU
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://authentication:7080/realms/bt-realm
    ports:
      - "8080:8080"
    networks:
      - local_network

  authentication:
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak
    depends_on:
      - db
    environment:
      KC_HOSTNAME: authentication
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info

      KC_IMPORT_FORCE: "true"
      KC_IMPORT: /opt/keycloak/data/import

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/testdb
      KC_DB_USERNAME: testU
      KC_DB_PASSWORD: pass

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    entrypoint: [ "sh", "-c" ]
    command: 
      - |
        /opt/keycloak/bin/kc.sh import --dir /opt/keycloak/data/import --override true --optimized
        /opt/keycloak/bin/kc.sh start-dev --http-port 7080 --https-port 7443
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - local_network
    volumes:
      - ./.keycloak/realms:/opt/keycloak/data/import:ro
      - ./.keycloak/theme:/opt/keycloak/themes/custom-theme
networks:
  local_network:
    driver: bridge

volumes:
  pgdata:
