#server:
#  port: 8080
#  address: 0.0.0.0

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/myrealm

#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE



